{{- if .Values.statefulSet.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "app.name" . }}
  {{- if not .Values.scaleToZero.enabled }}
  replicas: {{ .Values.statefulSet.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "app.podSpec" . | nindent 6 }}
  {{- with .Values.statefulSet.volumeClaimTemplates }}
  volumeClaimTemplates:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
